### PR TITLE
Presentation outline

### PR DESCRIPTION
**Pull request by jsonbecker**
#### What does this PR do?
* Merges in the outline of the presentation into the master branch.

#### What needs to be finished before QA?
- [ ] Is this up to date from each of the speakers?
- [ ] Nate
- [x] Billy
- [ ] Daphne
- [ ] Jason

#### Where should the reviewers start?
1. This is a single file change that should only alter the outline. Please review the README.md to make sure it accurately reflects the plans for your portion of the talk.

#### How should this be manually tested?
1. N/A

#### Any background context you want to provide?
* I found it difficult to work with many open branches separated by topic. Sometimes I open up a PR long before a branch is ready to keep it top of mind and get a great diff interface. I also don't think that we should have `long running branches`. This is an anti-partern.

#### What are the relevant tickets?
* N/A

#### Screenshots?

c4jt321

#### Questions:
* Please review before 12 pm on Wednesday so that our final coordination can be done prior to Thursday's presentation.

### CODE REVIEW

**Comment by wbuchanan** [comment]
@jsonbecker I definitely need to update things on my side.  Should be able to finalize the structure of things tomorrow.  Basically have several different subtopics that I want to trim based on any coverage of material that you'll do.  Also, Nathan put together a `hello world` repository that we could use to keep a consistent structure across any/all the demonstrations.

**Comment by nathant23** [comment]
@wbuchanan @jsonbecker 
If it works for you guys, I'm working on a markdown document that will have screenshots of what I go through live.  I will put highlights of what I talk about in the presentation slide deck so that it is not bogged down with screenshots.  Once I have it completed I will move it over to this repository.

**Comment by jsonbecker** [comment]
@nathant23 I'd almost rather we all fill in the markdown-level outline here versus have slides done or even prepared. As I went through my section again tonight, I realized that my `slides` would amount to little more than what's in this markdown doc (see bb616c4), and the rest I think are going to be example's I want to show.

Do we know if I'll be able to plug directly into the projector with my own machine? I think for my section in particular I want to do some work in a private repo that I show folks because a real example will work better than a contrived one (and have them work on a contrived example alongside based on the `hello_world` repo).

**Comment by wbuchanan** [comment]
@jsonbecker
Do you have any type of video splitter?  I could do something similar related to git reset and things like that but think we could run into difficulties if we are all switching between machines without having something in place to ensure the transitions are smooth.

**Comment by jsonbecker** [comment]
I don't usually have trouble if I'm just swapping a VGA or HDMI cable.

--
Jason Becker

**Review by wbuchanan — APPROVED** [review]
Removed reference to brewscheme at the end of Nathan's section since I'll talk a bit about submodules.  Pulled Jason's changes and pushed my outline.

**Pull request merged**
